Repository Richasy/Bili.Copilot, pull requests merged in 2023-08, with the labels that each got.

#18 适当放宽窗口高度限制
  src/App/App.xaml.cs
  src/App/Forms/MainWindow.xaml.cs
  src/Models/Models.Constants/App/SettingNames.cs
  src/ViewModels/Components/AppViewModel/AppViewModel.cs
Labels: enhancement

#22 修复用户信息解析问题
  src/App/Controls/Base/UserItem/UserItem.xaml
  src/Models/Models.BiliBili/User/UserSpaceResponse.cs
Labels: bug

#24 修复播放图标布局问题
  .github/release-drafter.yml
  src/App/Controls/Base/BiliTransportControls.xaml
Labels: bug

#28 修复 BBDown 配置读写问题
  src/App/App.csproj
  src/App/Assets/BBDown.config
  src/App/Controls/Base/DownloadSection.xaml
  src/App/Forms/MainWindow.xaml.cs
  src/App/Resources/zh-Hans/Resources.resw
  src/App/Resources/zh-Hant/Resources.resw
  src/Libs/Libs.Toolkit/FileToolkit.cs
  src/Models/Models.Constants/App/SettingNames.cs
  src/ViewModels/Components/DownloadModuleViewModel/DownloadModuleViewModel.Properties.cs
  src/ViewModels/Components/DownloadModuleViewModel/DownloadModuleViewModel.cs
  src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.cs
  src/ViewModels/WindowInjectionArgs.cs
Labels: bug

#39 修复播放详情的描述文本不可选的问题
  src/App/Controls/Modules/LiveInformationView.xaml
  src/App/Controls/Modules/PgcInformationView.xaml
  src/App/Controls/Modules/VideoInformationView.xaml
Labels: bug

#42 升级至 .net 8
  src/App/App.csproj
  src/Libs/Libs.Adapter/Libs.Adapter.csproj
  src/Libs/Libs.Flyleaf/Libs.Flyleaf.csproj
  src/Libs/Libs.Markdown/Libs.Markdown.csproj
  src/Libs/Libs.Provider/Libs.Provider.csproj
  src/Libs/Libs.Toolkit/Libs.Toolkit.csproj
  src/Models/Models.App/Models.App.csproj
  src/Models/Models.BiliBili/Models.BiliBili.csproj
  src/Models/Models.Constants/Models.Constants.csproj
  src/Models/Models.Data/Models.Data.csproj
  src/Models/Models.Grpc/Models.Grpc.csproj
  src/ViewModels/ViewModels.csproj
Labels: enhancement

#55 支持本机播放器
  Bili.Copilot.sln
  src/App/App.csproj
  src/App/App.xaml
  src/App/Assets/DashAudioWithoutVideoTemplate.xml
  src/App/Assets/DashVideoTemplate.xml
  src/App/Assets/DashVideoWithoutAudioTemplate.xml
  src/App/Controls/Base/BiliPlayer/BiliPlayer.cs
  src/App/Controls/Base/BiliPlayer/BiliPlayer.xaml
  src/App/Controls/Base/BiliPlayerOverlay/BiliPlayerOverlay.Handlers.cs
  src/App/Controls/Base/BiliPlayerOverlay/BiliPlayerOverlay.xaml
  src/App/Controls/Base/BiliTransportControls.xaml
  src/App/Controls/Modules/LiveInformationView.xaml
  src/App/Controls/Modules/PgcInformationView.xaml
  src/App/Controls/Modules/VideoInformationView.xaml
  src/App/Controls/Settings/PlayerControlSettingSection.xaml
  src/App/Converters/PlayerTypeConverter.cs
  src/App/Pages/LivePlayerPage.xaml
  src/App/Pages/PgcPlayerPage.xaml
  src/App/Pages/VideoPlayerPage.xaml
  src/Directory.Build.props
  src/Libs/Libs.Adapter/Libs.Adapter.csproj
  src/Libs/Libs.Flyleaf/Libs.Flyleaf.csproj
  src/Libs/Libs.Markdown/Libs.Markdown.csproj
  src/Libs/Libs.Provider/Libs.Provider.csproj
  src/Libs/Libs.Toolkit/Libs.Toolkit.csproj
  src/Models/Models.App/Constants/AppConstants.cs
  src/Models/Models.App/Models.App.csproj
  src/Models/Models.BiliBili/Models.BiliBili.csproj
  src/Models/Models.Constants/Models.Constants.csproj
  src/Models/Models.Data/Models.Data.csproj
  src/Models/Models.Grpc/Models.Grpc.csproj
  src/ViewModels/Components/FFmpegPlayerViewModel/FFmpegPlayerViewModel.Methods.cs
  src/ViewModels/Components/FFmpegPlayerViewModel/FFmpegPlayerViewModel.Properties.cs
  src/ViewModels/Components/FFmpegPlayerViewModel/FFmpegPlayerViewModel.cs
  src/ViewModels/Components/MediaPlayerViewModel/MediaPlayerViewModel.Properties.cs
  src/ViewModels/Components/NativePlayerViewModel/NativePlayerViewModel.Methods.cs
  src/ViewModels/Components/NativePlayerViewModel/NativePlayerViewModel.Properties.cs
  src/ViewModels/Components/NativePlayerViewModel/NativePlayerViewModel.cs
  src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.Method.cs
  src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.Properties.cs
  src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.Video.cs
  src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.cs
  src/ViewModels/IPlayerViewModel.cs
  src/ViewModels/ViewModels.csproj
  src/ViewModels/Views/LivePlayerPageViewModel/LivePlayerPageViewModel.Methods.cs
  src/ViewModels/Views/PgcPlayerPageViewModel/PgcPlayerPageViewModel.Methods.cs
  src/ViewModels/Views/SettingsPageViewModel/SettingsPageViewModel.Properties.cs
  src/ViewModels/Views/SettingsPageViewModel/SettingsPageViewModel.cs
  src/ViewModels/Views/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Methods.cs
Labels: enhancement

#56 修复下载问题
  src/ViewModels/Components/DownloadModuleViewModel/DownloadModuleViewModel.cs
Labels: bug

#57 修复循环播放未生效的问题
  Bili.Copilot.sln
  src/ViewModels/Components/FFmpegPlayerViewModel/FFmpegPlayerViewModel.Methods.cs
  src/ViewModels/Components/NativePlayerViewModel/NativePlayerViewModel.cs
  src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.cs
Labels: bug

#58 修复重复搜索的问题
  src/Libs/Libs.Provider/SearchProvider/SearchProvider.Extension.cs
  src/ViewModels/Views/SearchDetailViewModel/SearchDetailViewModel.Properties.cs
  src/ViewModels/Views/SearchDetailViewModel/SearchDetailViewModel.cs
Labels: bug

#60 修复用户信息获取异常导致的应用崩溃
  src/Models/Models.BiliBili/User/MyInfo.cs
Labels: bug

#65 支持固定条目
  Bili.Copilot.sln
  src/App/App.csproj
  src/App/Controls/Base/LiveItem/LiveItem.xaml
  src/App/Controls/Base/SeasonItem/SeasonItem.xaml
  src/App/Controls/Base/UserItem/UserItem.xaml
  src/App/Controls/Base/VideoItem/VideoItem.xaml
  src/App/Controls/Modules/FixModule.xaml
  src/App/Controls/Modules/FixModule.xaml.cs
  src/App/Controls/Modules/HotSearchModule.xaml
  src/App/Controls/Modules/HotSearchModule.xaml.cs
  src/App/Controls/Modules/SearchBoxModule.xaml
  src/App/Controls/Modules/SearchBoxModule.xaml.cs
  src/App/Converters/FixTypeIconConverter.cs
  src/App/Pages/HomePage.xaml
  src/App/Pages/HomePage.xaml.cs
  src/App/Resources/zh-Hans/Resources.resw
  src/App/Resources/zh-Hant/Resources.resw
  src/Models/Models.BiliBili/Article/Article.cs
  src/Models/Models.BiliBili/Article/ArticleCategory.cs
  src/Models/Models.BiliBili/Core/RecommendCard.cs
  src/Models/Models.BiliBili/Live/LiveAreaDetailResponse.cs
  src/Models/Models.BiliBili/Live/LiveRoomDetail.cs
  src/Models/Models.BiliBili/Others/ArticleFavoriteListResponse.cs
  src/Models/Models.BiliBili/Search/ArticleSearchItem.cs
  src/Models/Models.BiliBili/Search/UserSearchItem.cs
  src/Models/Models.BiliBili/Search/VideoSearchItem.cs
  src/Models/Models.BiliBili/User/Mine.cs
  src/Models/Models.BiliBili/User/UserRelation.cs
  src/Models/Models.Constants/App/FixedType.cs
  src/Models/Models.Constants/App/HomeCustomModuleType.cs
  src/Models/Models.Constants/App/SettingNames.cs
  src/ViewModels/Components/AppViewModel/AppViewModel.cs
  src/ViewModels/Components/FixModuleViewModel/FixModuleViewModel.Properties.cs
  src/ViewModels/Components/FixModuleViewModel/FixModuleViewModel.cs
  src/ViewModels/Items/LiveItemViewModel/LiveItemViewModel.cs
  src/ViewModels/Items/SeasonItemViewModel/SeasonItemViewModel.cs
  src/ViewModels/Items/UserItemViewModel/UserItemViewModel.cs
  src/ViewModels/Items/VideoItemViewModel/VideoItemViewModel.cs
  src/ViewModels/Views/HomePageViewModel.cs
Labels: enhancement

#66 修复最大化时的窗口高度
  src/App/App.xaml.cs
Labels: bug

#67 支持播放窗口大小记忆
  src/App/Forms/PlayerWindow.xaml.cs
  src/Models/Models.Constants/App/SettingNames.cs
Labels: enhancement

#68 修复循环播放起始点异常的问题
  src/ViewModels/Components/NativePlayerViewModel/NativePlayerViewModel.cs
  src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.Method.cs
Labels: bug

#69 历史记录新增观看时间戳显示
  src/Libs/Libs.Adapter/VideoAdapter.cs
Labels: enhancement

#82 保存播放器位置信息
  src/App/Forms/PlayerWindow.xaml.cs
  src/Models/Models.Constants/App/SettingNames.cs
Labels: enhancement

#83 支持下载路径自定义
  src/ViewModels/Components/DownloadModuleViewModel/DownloadModuleViewModel.cs
Labels: enhancement

#84 替换二维码生成器
  src/App/App.csproj
  src/Libs/Libs.Adapter/Libs.Adapter.csproj
  src/Libs/Libs.Flyleaf/Libs.Flyleaf.csproj
  src/Libs/Libs.Markdown/Libs.Markdown.csproj
  src/Libs/Libs.Provider/AuthorizeProvider/AuthorizeProvider.cs
  src/Libs/Libs.Provider/Libs.Provider.csproj
  src/Libs/Libs.Toolkit/Libs.Toolkit.csproj
  src/Models/Models.Grpc/Models.Grpc.csproj
  src/ViewModels/ViewModels.csproj
Labels: maintain

#94 修复动态点赞不生效的问题
  src/App/Controls/Base/DynamicItem/DynamicItem.xaml
  src/Libs/Libs.Provider/CommunityProvider/CommunityProvider.cs
  src/Models/Models.App/Constants/ApiConstants.cs
  src/Models/Models.Grpc/bilibili/app/dynamic/v2/dynamic.proto
  src/ViewModels/Items/DynamicItemViewModel/DynamicItemViewModel.cs
Labels: bug

#99 添加左侧菜单布局
  src/App/App.csproj
  src/App/Controls/AppTitleBar.xaml
  src/App/Controls/AppTitleBar.xaml.cs
  src/App/Controls/Modules/MessageDetailModule.xaml
  src/App/Controls/Settings/MenuPositionSettingSection.xaml
  src/App/Controls/Settings/MenuPositionSettingSection.xaml.cs
  src/App/Forms/MainWindow.xaml
  src/App/Forms/MainWindow.xaml.cs
  src/App/Pages/SettingsPage.xaml
  src/App/Resources/zh-Hans/Resources.resw
  src/App/Resources/zh-Hant/Resources.resw
  src/App/TraceLogger.cs
  src/Libs/Libs.Provider/Libs.Provider.csproj
  src/Models/Models.App/Other/NavigateItem.cs
  src/Models/Models.Constants/App/MenuPosition.cs
  src/Models/Models.Constants/App/SettingNames.cs
  src/ViewModels/Components/AppViewModel/AppViewModel.cs
  src/ViewModels/Views/SettingsPageViewModel/SettingsPageViewModel.Properties.cs
  src/ViewModels/Views/SettingsPageViewModel/SettingsPageViewModel.cs
  src/ViewModels/Views/WatchlistPageViewModel/WatchlistPageViewModel.cs
Labels: enhancement

#96 播放结束后自动关闭播放器
  src/App/Controls/Settings/PlayerModeSettingSection.xaml
  src/App/Resources/zh-Hans/Resources.resw
  src/App/Resources/zh-Hant/Resources.resw
  src/Models/Models.Constants/App/SettingNames.cs
  src/ViewModels/Views/SettingsPageViewModel/SettingsPageViewModel.Properties.cs
  src/ViewModels/Views/SettingsPageViewModel/SettingsPageViewModel.cs
  src/ViewModels/Views/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Methods.cs
Labels: enhancement

#95 收藏夹列表的标题中增加总数
  src/App/Controls/Modules/VideoFavoriteModule.xaml
Labels: enhancement

#101 添加播放器类型数据采集
  src/App/Controls/Modules/VideoFavoriteModule.xaml
  src/App/Forms/PlayerWindow.xaml.cs
  src/App/TraceLogger.cs
Labels: maintain
