Repository Richasy/Bili.Copilot, pull requests merged in 2024-09, with the labels that each got.

#475 修复切换分P选中项没有刷新的问题
  src/Desktop/BiliCopilot.UI/Controls/Core/PlayerNotificationControl.xaml
  src/Desktop/BiliCopilot.UI/Controls/Player/VideoPartsSection.xaml.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Components/VideoPlayerPartSectionDetailViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Events.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Operations.cs
Labels: bug

#476 修复字幕初始大小
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Methods.cs
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.cs
  src/Desktop/BiliCopilot.UI/Controls/Player/SubtitlePresenter.xaml
Labels: bug

#477 默认播放器调整为原生
  src/Desktop/BiliCopilot.UI/Properties/PublishProfiles/win-arm64.pubxml
  src/Desktop/BiliCopilot.UI/Properties/PublishProfiles/win-x64.pubxml
  src/Desktop/BiliCopilot.UI/ViewModels/Core/AppViewModel/AppViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/PlayerPageViewModelBase.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.cs
Labels: maintain

#478 给综合动态添加“在浏览器中打开”的选项
  src/Desktop/BiliCopilot.UI/Controls/Components/MomentCardControl/MomentCardControl.xaml
  src/Desktop/BiliCopilot.UI/Controls/Moment/MomentImageGallery.xaml.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Items/MomentItemViewModel/MomentItemViewModel.cs
Labels: enhancement

#483 修复稍后再看重复视频的问题
  src/Desktop/BiliCopilot.UI/ViewModels/View/ViewLaterPageViewModel/ViewLaterPageViewModel.cs
Labels: bug

#494 新的视频发布时间显示
  src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Methods.cs
Labels: enhancement

#495 修复应用窗口激活重定向问题
  src/Desktop/BiliCopilot.UI/App.xaml.cs
Labels: bug

#501 修复多行字幕重叠的问题
  src/Desktop/BiliCopilot.UI/BiliCopilot.UI.csproj
  src/Desktop/BiliCopilot.UI/Controls/Player/SubtitlePresenter.xaml
  src/Directory.Packages.props
Labels: bug

#502 更多添加到稍后再看的功能入口
  src/Desktop/BiliCopilot.UI/Controls/Components/MomentCardControl/MomentCardControl.xaml
  src/Desktop/BiliCopilot.UI/Controls/Player/VideoPlayerMainHeader.xaml
  src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Operations.cs
Labels: enhancement

#503 记住上一次选中的动态/用户空间区块
  src/Desktop/BiliCopilot.UI.Models/Constants/SettingNames.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/MomentPageViewModel/MomentPageViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/UserSpacePageViewModel/UserSpacePageViewModel.cs
Labels: enhancement

#505 引用更新，简化 opengl 渲染代码
  src/Desktop/BiliCopilot.UI/Controls/Core/Common/FrameBuffer.cs
  src/Directory.Packages.props
Labels: maintain

#506 折叠关注的直播间列表
  src/Desktop/BiliCopilot.UI/Controls/Components/LiveCardControl/LiveCardControl.xaml
  src/Desktop/BiliCopilot.UI/Controls/LivePartition/LivePartitionMainHeader.xaml
  src/Desktop/BiliCopilot.UI/Controls/LivePartition/LivePartitionMainHeader.xaml.cs
  src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
  src/Desktop/BiliCopilot.UI/ViewModels/Items/LiveItemViewModel/LiveItemViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/LivePartitionPageViewModel/LivePartitionPageViewModel.Properties.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/LivePartitionPageViewModel/LivePartitionPageViewModel.cs
Labels: enhancement

#515 增强播放速率调整（最高6倍速，步幅0.1）
  src/Desktop/BiliCopilot.UI/Controls/Core/TransportControl/VideoTransportControl.xaml
  src/Desktop/BiliCopilot.UI/Controls/Settings/PlayerControlSettingControl.xaml
  src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
  src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Properties.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/ArticleReaderPageViewModel/ArticleReaderPageViewModel.cs
Labels: enhancement

#516 修复弹幕在高缩放下的模糊问题
  src/Libs/Danmaku.Core/DanmakuRender.cs
Labels: bug

#517 弹幕速度与播放速率同步
  src/Desktop/BiliCopilot.UI/Controls/Danmaku/VideoDanmakuPanel.xaml.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/DanmakuViewModel/DanmakuViewModel.Properties.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/DanmakuViewModel/DanmakuViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/MpvPlayerViewModel/MpvPlayerViewModel.Overrides.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/NativePlayerViewModel/NativePlayerViewModel.Overrides.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/NativePlayerViewModel/NativePlayerViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Commands.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Properties.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/PgcPlayerPageViewModel/PgcPlayerPageViewModel.Operations.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/PgcPlayerPageViewModel/PgcPlayerPageViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Operations.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.cs
  src/Libs/Danmaku.Core/DanmakuFrostMaster.cs
  src/Libs/Danmaku.Core/DanmakuRender.cs
Labels: bug

#518 播放器触摸优化
  src/Desktop/BiliCopilot.UI.Models/Constants/PlayerManipulationType.cs
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Methods.cs
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.cs
Labels: enhancement

#526 修复全屏播放时底部白线
  src/Desktop/BiliCopilot.UI/Controls/AI/AIBody.xaml
  src/Desktop/BiliCopilot.UI/Controls/Core/Common/RenderControl.cs
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.cs
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.xaml
  src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.cs
Labels: enhancement

#527 添加更新提示
  src/Desktop/BiliCopilot.UI.Models/Constants/SettingNames.cs
  src/Desktop/BiliCopilot.UI/Controls/RootLayout.xaml
  src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
  src/Desktop/BiliCopilot.UI/ViewModels/Components/AccountViewModel/AccountViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/AppViewModel/AppViewModel.Properties.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/AppViewModel/AppViewModel.cs
Labels: enhancement

#536 修复 WebDAV 在全窗口/全屏下没有撑满容器的问题
  src/Desktop/BiliCopilot.UI/Pages/Overlay/WebDavPlayerPage.xaml
Labels: bug

#540 支持字幕下载（不包括 AI 字幕）
  src/Desktop/BiliCopilot.UI/Controls/Player/DownloadButton.xaml
  src/Desktop/BiliCopilot.UI/Controls/Player/DownloadButton.xaml.cs
  src/Desktop/BiliCopilot.UI/Controls/Settings/PlayerControlSettingControl.xaml
  src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
  src/Desktop/BiliCopilot.UI/ViewModels/Core/DownloadViewModel/DownloadViewModel.Properties.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/DownloadViewModel/DownloadViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/SubtitleViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Methods.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.cs
Labels: enhancement

#548 支持鼠标侧键返回
  src/Desktop/BiliCopilot.UI/Controls/RootLayout.xaml.cs
  src/Desktop/BiliCopilot.UI/Forms/MainWindow.xaml.cs
  src/Desktop/BiliCopilot.UI/Forms/PlayerWindow.xaml.cs
  src/Desktop/BiliCopilot.UI/NativeMethods.txt
Labels: enhancement

#549 支持默认以新窗口打开视频
  src/Desktop/BiliCopilot.UI.Models/Constants/PlayerDisplayMode.cs
  src/Desktop/BiliCopilot.UI/Converters/DisplayModeConverter.cs
  src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
  src/Desktop/BiliCopilot.UI/ViewModels/Items/EpisodeItemViewModel/EpisodeItemViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Items/LiveItemViewModel/LiveItemViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Items/MomentItemViewModel/MomentItemViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Items/SeasonItemViewModel/SeasonItemViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Items/VideoItemViewModel/VideoItemViewModel.cs
Labels: enhancement

#550 支持配置是否跳过 AI 字幕下载
  src/Desktop/BiliCopilot.UI.Models/Constants/SettingNames.cs
  src/Desktop/BiliCopilot.UI/Controls/Settings/DownloadSettingControl.xaml
  src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
  src/Desktop/BiliCopilot.UI/ViewModels/Core/DownloadViewModel/DownloadViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.Properties.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Methods.cs
Labels: enhancement

#561 支持循环播放
  src/Desktop/BiliCopilot.UI.Models/Constants/SettingNames.cs
  src/Desktop/BiliCopilot.UI.Models/Constants/VideoLoopType.cs
  src/Desktop/BiliCopilot.UI/App.xaml.cs
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.cs
  src/Desktop/BiliCopilot.UI/Controls/Danmaku/VideoDanmakuPanel.xaml.cs
  src/Desktop/BiliCopilot.UI/Controls/Player/VideoOperationControl.xaml
  src/Desktop/BiliCopilot.UI/Controls/Player/VideoOperationControl.xaml.cs
  src/Desktop/BiliCopilot.UI/Controls/Player/VideoPlaylistSection.xaml.cs
  src/Desktop/BiliCopilot.UI/Controls/Player/VideoSeasonSection.xaml.cs
  src/Desktop/BiliCopilot.UI/Controls/Settings/PlayerBehaviorSettingControl.xaml
  src/Desktop/BiliCopilot.UI/Converters/LoopTypeConverter.cs
  src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
  src/Desktop/BiliCopilot.UI/ViewModels/Core/DanmakuViewModel/DanmakuViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/MpvPlayerViewModel/MpvPlayerViewModel.Overrides.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Properties.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/LivePlayerPageViewModel/LivePlayerPageViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/PgcPlayerPageViewModel/PgcPlayerPageViewModel.Operations.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/PgcPlayerPageViewModel/PgcPlayerPageViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.Properties.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Methods.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Operations.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Properties.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/WebDavPlayerPageViewModel/WebDavPlayerPageViewModel.Operations.cs
Labels: enhancement

#569 移除资讯分区排行榜（因为不存在）
  src/Desktop/BiliCopilot.UI/ViewModels/View/PopularPageViewModel/PopularPageViewModel.Requests.cs
Labels: bug

#572 调整推荐视频的标签显示
  src/Desktop/BiliCopilot.UI/Controls/Components/VideoCardControl/VideoCardControl.xaml
Labels: bug

#573 移除推荐文章分区
  src/Desktop/BiliCopilot.UI/ViewModels/View/ArticlePartitionPageViewModel/ArticlePartitionPageViewModel.cs
Labels: enhancement

#576 AI 页面添加配置提示
  src/Desktop/BiliCopilot.UI/Pages/SettingsPage.xaml
  src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
Labels: enhancement

#589 延迟播放器尺寸变化
  src/Desktop/BiliCopilot.UI/BiliCopilot.UI.csproj
  src/Desktop/BiliCopilot.UI/Controls/Components/UserCardControl/UserCardControl.cs
  src/Desktop/BiliCopilot.UI/Controls/Components/UserCardControl/UserCardControl.xaml
  src/Desktop/BiliCopilot.UI/Pages/Overlay/LivePlayerPage.xaml.cs
  src/Desktop/BiliCopilot.UI/Pages/Overlay/PgcPlayerPage.xaml.cs
  src/Desktop/BiliCopilot.UI/Pages/Overlay/VideoPlayerPage.xaml.cs
  src/Desktop/BiliCopilot.UI/Properties/PublishProfiles/win-arm64.pubxml
  src/Desktop/BiliCopilot.UI/Properties/PublishProfiles/win-x64.pubxml
  src/Desktop/BiliCopilot.UI/Properties/PublishProfiles/win-x86.pubxml
  src/Desktop/BiliCopilot.UI/Toolkits/FileToolkit.cs
Labels: bug

#590 修复图片复制问题
  src/Desktop/BiliCopilot.UI/Forms/GalleryWindow.xaml.cs
  src/Desktop/BiliCopilot.UI/Pages/GalleryPage.xaml
  src/Desktop/BiliCopilot.UI/ViewModels/View/GalleryPageViewModel/GalleryPageViewModel.cs
Labels: bug

#591 对于在 AMD 平台尝试使用内置 mpv 播放器的用户进行不兼容提醒
  src/Desktop/BiliCopilot.UI.Models/Constants/SettingNames.cs
  src/Desktop/BiliCopilot.UI/BiliCopilot.UI.csproj
  src/Desktop/BiliCopilot.UI/Controls/Settings/PlayerBehaviorSettingControl.xaml
  src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
  src/Desktop/BiliCopilot.UI/ViewModels/Core/AppViewModel/AppViewModel.Properties.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/AppViewModel/AppViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/MpvPlayerViewModel/MpvPlayerViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Properties.cs
  src/Directory.Packages.props
Labels: enhancement

#592 修复原生播放器下弹幕加载导致线程阻塞的问题
  src/Desktop/BiliCopilot.UI/Controls/Danmaku/VideoDanmakuPanel.xaml
  src/Desktop/BiliCopilot.UI/ViewModels/Core/DownloadViewModel/DownloadViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/PgcPlayerPageViewModel/PgcPlayerPageViewModel.Operations.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Operations.cs
Labels: bug

#593 进入新窗口播放时遵循默认播放模式
  src/Desktop/BiliCopilot.UI/Forms/MainWindow.xaml.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.cs
  src/Libs/Danmaku.Core/DanmakuFrostMaster.cs
Labels: bug

#595 临时修复弹幕表现
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.cs
  src/Desktop/BiliCopilot.UI/Pages/Overlay/VideoPlayerPage.xaml.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/MpvPlayerViewModel/MpvPlayerViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/LivePlayerPageViewModel/LivePlayerPageViewModel.Operations.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/LivePlayerPageViewModel/LivePlayerPageViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/PgcPlayerPageViewModel/PgcPlayerPageViewModel.Operations.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/PgcPlayerPageViewModel/PgcPlayerPageViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Operations.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.cs
  src/Libs/Danmaku.Core/DanmakuRender.cs
Labels: bug

#601 修复评论详情溢出文本未更新的问题
  src/Desktop/BiliCopilot.UI/Controls/Components/EmoteTextBlock.xaml
  src/Desktop/BiliCopilot.UI/Controls/Components/EmoteTextBlock.xaml.cs
Labels: bug

#604 使用 GeneratedComInterface 来生成 COM 接口
  src/Desktop/BiliCopilot.UI/BiliCopilot.UI.csproj
  src/Desktop/BiliCopilot.UI/Controls/Core/Common/ISwapChainPanelNative.cs
Labels: maintain

#607 修复外部播放器的绑定问题
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/ExternalPlayer.cs
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/PlayerResources.xaml
  src/Desktop/BiliCopilot.UI/ViewModels/Core/MpvPlayerViewModel/MpvPlayerViewModel.cs
  src/Libs/Danmaku.Core/DanmakuFrostMaster.cs
Labels: bug

#611 修复 webdav 配置没有正确读取的问题
  src/Desktop/BiliCopilot.UI/Toolkits/FileToolkit.cs
Labels: bug

#616 修复弹幕加速异常
  src/Desktop/BiliCopilot.UI/Controls/Danmaku/VideoDanmakuPanel.xaml.cs
Labels: bug

#617 修复进入播放独占模式时的卡顿问题
  src/Desktop/BiliCopilot.UI/Pages/Overlay/LivePlayerPage.xaml.cs
  src/Desktop/BiliCopilot.UI/Pages/Overlay/PgcPlayerPage.xaml.cs
  src/Desktop/BiliCopilot.UI/Pages/Overlay/VideoPlayerPage.xaml.cs
Labels: bug

#618 修复通知消息条目跳转问题
  src/Desktop/BiliCopilot.UI/Controls/Components/NotifyMessageCardControl/NotifyMessageCardControl.xaml
Labels: bug

#641 修复视频画面因弹幕而消失的问题
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Methods.cs
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.xaml
  src/Desktop/BiliCopilot.UI/ViewModels/Core/MpvPlayerViewModel/MpvPlayerViewModel.Overrides.cs
Labels: bug

#642 修复高清（1080）选择顺序
  src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Methods.cs
Labels: bug

#643 优化播放控制器触发逻辑
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Methods.cs
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.cs
Labels: bug, enhancement

#645 修复原生播放器暂停状态下不能通过快捷键调整进度的问题
  src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
  src/Desktop/BiliCopilot.UI/ViewModels/Core/NativePlayerViewModel/NativePlayerViewModel.Overrides.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Events.cs
Labels: bug

#646 修复仅窗口高度变化时播放器大小没有更新的问题
  src/Desktop/BiliCopilot.UI/Controls/Danmaku/VideoDanmakuPanel.xaml.cs
  src/Desktop/BiliCopilot.UI/Pages/Overlay/LivePlayerPage.xaml
  src/Desktop/BiliCopilot.UI/Pages/Overlay/PgcPlayerPage.xaml
  src/Desktop/BiliCopilot.UI/Pages/Overlay/VideoPlayerPage.xaml
Labels: bug

#647 修复退出播放独占后，直播消息列表没有滚动到底部的问题
  src/Desktop/BiliCopilot.UI/ViewModels/Components/LiveChatSectionDetailViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Commands.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Properties.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/LivePlayerPageViewModel/LivePlayerPageViewModel.Methods.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/LivePlayerPageViewModel/LivePlayerPageViewModel.cs
Labels: bug

#648 修正哔哩助理 AI 能力文案
  README.md
  src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
Labels: bug

#650 修复顶部导航在切换主页面时依然选中的问题
  src/Desktop/BiliCopilot.UI/ViewModels/Core/NavigationViewModel.cs
Labels: bug

#655 [临时] 修复弹幕重绘后消失的问题
  src/Desktop/BiliCopilot.UI/ViewModels/Core/DanmakuViewModel/DanmakuViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/LivePlayerPageViewModel/LivePlayerPageViewModel.Operations.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/PgcPlayerPageViewModel/PgcPlayerPageViewModel.Operations.cs
  src/Libs/Danmaku.Core/Logger.cs
Labels: bug

#671 进入全窗口/小窗模式时显示标题栏
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/IslandPlayer.Win32.cs
  src/Desktop/BiliCopilot.UI/Controls/RootLayout.xaml
  src/Desktop/BiliCopilot.UI/Controls/RootLayout.xaml.cs
  src/Desktop/BiliCopilot.UI/Forms/IFullScreenToggleWindow.cs
  src/Desktop/BiliCopilot.UI/Forms/MainWindow.xaml.cs
  src/Desktop/BiliCopilot.UI/Forms/PlayerWindow.xaml.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/AppViewModel/AppViewModel.cs
Labels: enhancement

#672 关闭全局播放速率后重置速率为1
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Create.cs
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.cs
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/IslandPlayer.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.cs
  src/Libs/Danmaku.Core/DanmakuRender.cs
Labels: bug

#674 修复 WebDAV 空格没有暂停的问题
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Create.cs
  src/Desktop/BiliCopilot.UI/Controls/RootLayout.xaml.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/IslandPlayerViewModel/IslandPlayerViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/MpvPlayerViewModel/MpvPlayerViewModel.cs
Labels: bug

#675 播放视频时，AI面板改作弹出层
  src/Desktop/BiliCopilot.UI.Models/Constants/MTCBehavior.cs
  src/Desktop/BiliCopilot.UI.Models/Constants/SettingNames.cs
  src/Desktop/BiliCopilot.UI/BiliCopilot.UI.csproj
  src/Desktop/BiliCopilot.UI/BiliCopilot.UI.csproj.user
  src/Desktop/BiliCopilot.UI/Controls/AI/AIFooter.xaml
  src/Desktop/BiliCopilot.UI/Controls/AI/AIHeader.xaml
  src/Desktop/BiliCopilot.UI/Controls/AI/AIOverlayPanel.xaml
  src/Desktop/BiliCopilot.UI/Controls/AI/AIPanel.xaml
  src/Desktop/BiliCopilot.UI/Controls/AI/AIPanel.xaml.cs
  src/Desktop/BiliCopilot.UI/Controls/Player/VideoPlayerMainHeader.xaml
  src/Desktop/BiliCopilot.UI/Controls/Player/VideoPlayerMainHeader.xaml.cs
  src/Desktop/BiliCopilot.UI/Pages/Overlay/VideoPlayerPage.xaml
  src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.Properties.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Operations.cs
Labels: enhancement

#676 支持播放控制器弹出方式设置
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Create.cs
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Methods.cs
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.cs
  src/Desktop/BiliCopilot.UI/Controls/Settings/PlayerControlSettingControl.xaml
  src/Desktop/BiliCopilot.UI/Converters/MTCBehaviorConverter.cs
  src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
Labels: enhancement

#678 支持调整 AI 响应类型（全文或流式）
  src/Desktop/BiliCopilot.UI.Models/Constants/SettingNames.cs
  src/Desktop/BiliCopilot.UI/BiliCopilot.UI.csproj
  src/Desktop/BiliCopilot.UI/BiliCopilot.UI.csproj.user
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Create.cs
  src/Desktop/BiliCopilot.UI/Controls/Settings/AIResponseSettingControl.xaml
  src/Desktop/BiliCopilot.UI/Controls/Settings/AIResponseSettingControl.xaml.cs
  src/Desktop/BiliCopilot.UI/Forms/PlayerWindow.xaml.cs
  src/Desktop/BiliCopilot.UI/Package.appxmanifest
  src/Desktop/BiliCopilot.UI/Pages/SettingsPage.xaml
  src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
  src/Desktop/BiliCopilot.UI/ViewModels/Core/AIViewModel/AIViewModel.Chat.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Items/EpisodeItemViewModel/EpisodeItemViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Items/LiveItemViewModel/LiveItemViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Items/MomentItemViewModel/MomentItemViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Items/SeasonItemViewModel/SeasonItemViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Items/VideoItemViewModel/VideoItemViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/PlayerPageViewModelBase.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.Properties.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Methods.cs
Labels: enhancement

#680 修复点击播放列表内的视频依然会在新窗口播放的问题
  src/Desktop/BiliCopilot.UI/Controls/Player/VideoPlaylistSection.xaml.cs
  src/Desktop/BiliCopilot.UI/Controls/Player/VideoSeasonSection.xaml.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Components/VideoPlayerPlaylistSectionDetailViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Components/VideoPlayerSeasonSectionDetailViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/PgcPlayerPageViewModel/PgcPlayerPageViewModel.Methods.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Methods.cs
Labels: bug

#686 设置弹幕边距，避免渲染问题
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Create.cs
Labels: bug

#690 支持针对岛播放器调整硬解类型
  src/Desktop/BiliCopilot.UI.Models/Constants/PreferDecodeType.cs
  src/Desktop/BiliCopilot.UI/Controls/Settings/PlayerBehaviorSettingControl.xaml
  src/Desktop/BiliCopilot.UI/Controls/Settings/PlayerControlSettingControl.xaml
  src/Desktop/BiliCopilot.UI/Converters/PreferDecodeTypeConverter.cs
  src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
  src/Desktop/BiliCopilot.UI/ViewModels/Core/IslandPlayerViewModel/IslandPlayerViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/MpvPlayerViewModel/MpvPlayerViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.Properties.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.cs
Labels: enhancement

#692 修复评论弹出层被播放器遮挡的问题
  src/Desktop/BiliCopilot.UI/Controls/Components/EmoteTextBlock.xaml
Labels: bug

#693 提前清除播放资源
  src/Desktop/BiliCopilot.UI/Pages/Overlay/LivePlayerPage.xaml.cs
  src/Desktop/BiliCopilot.UI/Pages/Overlay/PgcPlayerPage.xaml.cs
  src/Desktop/BiliCopilot.UI/Pages/Overlay/VideoPlayerPage.xaml.cs
  src/Desktop/BiliCopilot.UI/Pages/Overlay/WebDavPlayerPage.xaml.cs
Labels: bug

#695 修复岛播放器在退出后没有触发窗口关闭的问题
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/IslandPlayer.Win32.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/IslandPlayerViewModel/IslandPlayerViewModel.Overrides.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/MpvPlayerViewModel/MpvPlayerViewModel.Overrides.cs
Labels: bug

#696 修复侧键返回逻辑
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Methods.cs
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/IslandPlayer.Win32.cs
Labels: bug

#700 添加播放封面
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.xaml
  src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Properties.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.cs
Labels: enhancement

#701 修复播放列表无法点击切换的问题
  src/Desktop/BiliCopilot.UI/ViewModels/Components/VideoPlayerPlaylistSectionDetailViewModel.cs
Labels: bug

#704 在进入播放独占模式时，在标题栏上显示返回按钮
  src/Desktop/BiliCopilot.UI/Controls/RootLayout.xaml
  src/Desktop/BiliCopilot.UI/Controls/RootLayout.xaml.cs
  src/Desktop/BiliCopilot.UI/Forms/PlayerWindow.xaml
  src/Desktop/BiliCopilot.UI/Forms/PlayerWindow.xaml.cs
Labels: enhancement

#709 修复岛播放器初始化时的父窗口选择
  src/Desktop/BiliCopilot.UI/Controls/Core/Player/IslandPlayer.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Properties.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/PlayerPageViewModelBase.cs
Labels: bug

#710 修复收藏夹/稍后再看的播放全部没有遵循播放行为偏好的问题
  src/Desktop/BiliCopilot.UI/Forms/PlayerWindow.xaml.cs
  src/Desktop/BiliCopilot.UI/ViewModels/Components/VideoFavoriteSectionDetailViewModel/VideoFavoriteSectionDetailViewModel.cs
  src/Desktop/BiliCopilot.UI/ViewModels/View/ViewLaterPageViewModel/ViewLaterPageViewModel.cs
Labels: bug

#711 修复岛播放器全局速率可能不成功的问题
  src/Desktop/BiliCopilot.UI/ViewModels/Core/IslandPlayerViewModel/IslandPlayerViewModel.Overrides.cs
Labels: bug

#713 修复 Ollama 终结点没有正确显示的问题
  src/Desktop/BiliCopilot.UI/Controls/Settings/ModelClientEndpointConfigSettingSection.xaml.cs
Labels: bug
